name: Continuous Integration for Laravel Dusk
on:
  push:
  workflow_dispatch:
    inputs:
      browser:
        type: choice
        description: Which browser to test
        required: true
        default: chrome
        options:
          - chrome
          - firefox
          - edge

jobs:
  dusk-php:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest  # Usando 'chrome' diretamente para teste
        ports:
          - "4444:4444"
        options: >-
          --shm-size=2g

      mysql:
        image: mariadb:10.2
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: dusk
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Copy .env
        run: cp .env.example .env

      - name: Run migrations
        run: php artisan migrate --force

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'

      - name: Install Composer Dependencies
        run: |
          composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader
          chmod -R 777 storage bootstrap/cache
          npm install
          npm run dev

      - name: Install Dusk
        run: |
          composer require laravel/dusk --dev
          php artisan dusk:install
          
      - name: Wait for Selenium
        run: |
          for i in {1..30}; do
            nc -z selenium 4444 && echo "Selenium is up" && exit 0
            echo "Waiting for Selenium..."
            sleep 1
          done
          echo "Selenium did not start in time" && exit 1

      - name: Run Dusk Tests
        env:
          APP_URL: http://localhost
          DUSK_DRIVER_URL: http://selenium:4444/wd/hub
          APP_ENV: local
          DB_CONNECTION: mysql
          DB_DATABASE: dusk
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
          DB_USER: root
        run: php artisan dusk --env=testing
        
