
name: Continuos Integration for Laravel Dusk
on: [push]
jobs:

  dusk-php:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install Composer Dependencies
        run: |
          composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader
          chmod -R 777 storage bootstrap/cache
          npm install
          
      - name: Run Dusk Tests
        run: |
          php artisan dusk
        env:
          APP_ENV: local
          APP_URL: "http://localhost"
          DB_CONNECTION: pgsql
          DB_DATABASE: livetest
          DB_PORT: 5432
          DB_USER: sail
          DB_PASSWORD: password
