
name: Continuos Integration for Laravel Dusk
on: [push]
jobs:

  dusk-php:
    runs-on: ubuntu-latest

    services:

       selenium:
        image: selenium/standalone-chrome
        ports:
          - "4444:4444"
       
       mysql:
        image: mariadb:10.2
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: dusk
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3.9'

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install Composer Dependencies
        run: |
          composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader
          chmod -R 777 storage bootstrap/cache
          npm install
          npm run dev

      - name: Install Dusk
        run: |
          composer require laravel/dusk --dev
          php artisan dusk:install

      - name: Run Laravel Server
        run: php artisan serve --host=0.0.0.0 --port=8000 > /dev/null 2>&1 &

      - name: Check Selenium Status
        run: curl http://selenium:4444/wd/hub/status

      - name: Run Dusk Tests
        run: |
          chmod -R 0755 vendor/laravel/dusk/bin/
          php artisan dusk
          
        env:
          APP_ENV: local
          DUSK_DRIVER_URL: "http://selenium:4444/wd/hub"
          APP_URL: "http://localhost:8000"
          DB_CONNECTION: mysql
          DB_DATABASE: dusk
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
          DB_USER: root
