
name: Continuos Integration for Laravel Dusk
on: [push]
jobs:

  dusk-php:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3.9'

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install Composer Dependencies
        run: |
          composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader
          chmod -R 777 storage bootstrap/cache
          npm install
          npm run dev
          
      - name: Upgrade Chrome Driver
        run: php artisan dusk:chrome-driver

      - name: Install Dusk
        run: |
          composer require laravel/dusk --dev
          php artisan dusk:install

      - name: Start Chrome Driver
        run: ./vendor/laravel/dusk/bin/chromedriver-linux > /dev/null 2>&1 &

      - name: Run Laravel Server
        run: php artisan serve > /dev/null 2>&1 &

      - name: Run Dusk Tests
        run: |
          chmod -R 0755 vendor/laravel/dusk/bin/
          php artisan dusk
          
        env:
          APP_ENV: local
          APP_URL: "http://localhost"
          DB_CONNECTION: pgsql
          DB_DATABASE: livetest
          DB_PORT: 5432
          DB_USER: sail
          DB_PASSWORD: password
